---
- name: Check to see if the swarm is initialized
  shell: docker info | grep -e '^Swarm' | cut -d ' ' -f 2
  register: swarm_active
  changed_when: False

- name: Initialize the swarm
  command: "docker swarm init --advertise-addr {{ ansible_eth0.ipv4.address }}"
  when: '"inactive" in swarm_active.stdout'

- name: Get the docker swarm token
  command: docker swarm join-token -q worker
  register: swarm_worker_token
  changed_when: False

- name: Set the worker token fact
  set_fact:
    swarm_worker_token: "{{ swarm_worker_token.stdout }}"
    swarm_master_ip: "{{ ansible_eth0.ipv4.address }}"

- name: Check to see if the docker viz is running
  command: docker service ps viz
  register: rswarm_viz_service
  changed_when: False

- name: Deploy Docker viz
  command: >
          docker service create \
                  --no-resolve-image \
                  --detach=False \
                  --name viz \
                  --publish 8080:8080/tcp \
                  --constraint node.role==manager \
                  --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
                  alexellis2/visualizer-arm:latest
  when: rswarm_viz_service.rc == 0
