---
- name: Check to see if the swarm is active
  shell: docker info | grep -e '^Swarm' | cut -d ' ' -f 2
  register: swarm_active
  changed_when: False

- name: Join hosts to the swarm
  command: >
    docker swarm join \
    --token {{ hostvars['swarmaster']['swarm_worker_token'] }} \
    {{ hostvars['swarmaster']['ansible_eth0']['ipv4']['address'] }}:2377
  when: '"inactive" in swarm_active.stdout'

- name: Set authorized key from file
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '/home/pi/.ssh/swarm_rsa.pub') }}"

- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  notify: ssh service

# This is a cheap workaround to this
# https://github.com/docker/swarmkit/issues/2294
# bug. When the figure it out we should be able to
# stop doing --no-resolve-image in our service creates
- name: Create a cron to pull latest docker images
  cron:
    name: "Pull the latest mols image"
    minute: "*/5"
    job: "docker pull champain/latin_squares:latest"
