---
- name: Go discover all of the hosts
  hosts: swarm_master
  become: True
  tasks:
    - name: set the hostname
      hostname:
        name: swarmaster

    - name: Apt update to install avahi-utils
      apt:
        name: avahi-utils
        update_cache: yes

    - name: Go discover all of the raspberry pis
      shell: >
        avahi-browse -a -t | awk '/IPv4 raspberrypi/ { print $4 }' | uniq
      register: avahi_discovered_pis
      changed_when: False

    - name: For each of the pis discovered, add it to the swarm_host group
      add_host:
        name: "{{ item }}.local"
        groups: swarm_hosts
      with_items: "{{ avahi_discovered_pis.stdout_lines }}"
      changed_when: False

- name: Include the common role
  hosts: swarm
  become: True
  roles:
    - common

- name: Inclue the master role
  hosts: swarm_master
  become: True
  roles:
     - swarm_master

- name: Include the host role
  hosts: swarm_hosts
  become: True
  roles:
    - swarm_host
