---
- name: Main docker playbook
  hosts: swarm_master:swarm_host
  become: True
  tasks:
    - name: Make sure the pi user is present
      user:
        name: pi
        generate_ssh_key: yes

    - template:
        src: ../templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
